"""
Complete options strategy library for Northstar V3.
"""

OPTION_STRATEGIES = {
    "protective_put": {
        "name": "Protective Put",
        "group": "defensive",
        "description": "Buy put on stock or index to protect long exposure.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0}
        ],
        "when_to_use": [
            "single stock with large position (>2% of portfolio) has negative company signal",
            "stock in sector scoring < -0.60 in sector_impact_vector",
            "cannot sell stock due to liquidity constraints",
            "conviction in underlying but fear of short-term macro shock",
        ],
        "when_not_to_use": [
            "IV rank > 80 - put premium too expensive",
            "position is < 0.5% of portfolio",
            "stock is in defensive sector during a bullish market",
        ],
        "entry_conditions": {"min_position_weight_pct": 1.0, "max_iv_rank": 80, "sector_impact_threshold": -0.40, "min_shock_severity": "MODERATE"},
        "exit_conditions": {"stop_loss_pct": 50, "target_pct": 150, "max_holding_days": 21, "exit_on_shock_resolution": True},
        "sizing": {"method": "delta_neutral", "max_cost_pct_of_position": 2.0},
        "shock_triggers": ["oil_price_spike", "oil_supply_disruption", "geopolitical_conflict", "fii_outflow", "rate_hike_rbi", "rate_hike_fed"],
        "preferred_underlyings": ["NIFTY", "BANKNIFTY", "individual_stocks_at_risk"],
        "notes": "Use bear spread instead when IV is already very rich.",
    },
    "bear_put_spread": {
        "name": "Bear Put Spread",
        "group": "defensive",
        "description": "Buy higher strike put and sell lower strike put for cheaper downside protection.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -2.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "put", "strike_offset_pct": -7.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "expecting moderate decline (3-8%)",
            "IV rank is elevated (>50)",
            "oil_supply_disruption or geopolitical conflict shock detected",
            "shock_severity >= HIGH",
            "primary portfolio hedge when market_level_impact < -0.020",
        ],
        "when_not_to_use": [
            "expecting extreme crash > 10%",
            "IV rank < 20",
            "very long-dated expiry",
        ],
        "entry_conditions": {"min_shock_severity": "HIGH", "estimated_nifty_move_pct_threshold": -2.0, "max_iv_rank": 90, "min_iv_rank": 30},
        "exit_conditions": {"stop_loss_pct": 60, "target_pct": 80, "max_holding_days": 15, "exit_if_shock_resolves": True},
        "sizing": {"method": "notional_pct", "max_portfolio_hedge_pct": 5.0, "lots_per_crore_exposure": 2},
        "max_profit": "difference between strikes minus net premium paid",
        "max_loss": "net premium paid",
        "breakeven": "upper strike minus net premium paid",
        "shock_triggers": ["oil_supply_disruption", "geopolitical_conflict", "fii_outflow", "rate_hike_fed", "global_recession"],
        "preferred_underlyings": ["NIFTY", "BANKNIFTY"],
        "notes": "Default shock hedge for high-severity bearish regimes.",
    },
    "ratio_put_spread": {
        "name": "Ratio Put Spread (1x2)",
        "group": "defensive",
        "description": "Buy one near-ATM put and sell two farther OTM puts for crash convexity at low net cost.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -1.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "put", "strike_offset_pct": -8.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 2.0},
        ],
        "when_to_use": [
            "shock_severity == SEVERE or EXTREME",
            "flash crash or panic scenario",
            "hedge budget is constrained",
            "IV is already extremely high",
        ],
        "when_not_to_use": [
            "controlled moderate decline",
            "low liquidity in far OTM puts",
            "if position cannot be monitored intraday",
        ],
        "entry_conditions": {"min_shock_severity": "SEVERE", "min_iv_regime": "HIGH", "vix_level_min": 22},
        "exit_conditions": {"stop_loss_trigger": "if market falls below lower strike, close extra short immediately", "target_pct": 70, "max_holding_days": 10},
        "sizing": {"method": "notional_pct", "max_portfolio_hedge_pct": 3.0, "note": "Use sparingly because downside beyond the short strike is uncovered."},
        "max_profit": "near the short strike",
        "max_loss": "unlimited below lower strike",
        "shock_triggers": ["oil_supply_disruption", "geopolitical_conflict", "global_recession", "unknown_high_magnitude"],
        "preferred_underlyings": ["NIFTY"],
        "notes": "Emergency tail hedge only.",
    },
    "collar": {
        "name": "Collar",
        "group": "defensive",
        "description": "Buy OTM put and finance it with an OTM covered call sale.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "call", "strike_offset_pct": +5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "large individual stock position (>3% portfolio) with negative shock signal",
            "cannot sell the stock immediately",
            "long-term conviction but near-term event risk",
            "dividend-paying stock where ownership must be retained",
        ],
        "when_not_to_use": [
            "expecting explosive upside",
            "high-momentum bullish regime",
        ],
        "entry_conditions": {"min_position_weight_pct": 2.0, "min_shock_severity": "MODERATE"},
        "exit_conditions": {"stop_loss_pct": 40, "target_pct": 80, "max_holding_days": 30, "unwind_trigger": "shock resolves and stock recovers above short call strike"},
        "sizing": {"method": "match_equity_lots", "target_net_premium": "zero or small debit"},
        "shock_triggers": ["oil_price_spike", "fii_outflow", "rate_hike_rbi", "geopolitical_conflict"],
        "preferred_underlyings": ["large_cap_holdings", "Financial Services", "IT"],
        "notes": "Free or low-cost stock hedge with capped upside.",
    },
    "delta_hedge_synthetic": {
        "name": "Delta Hedge (Synthetic Short via Futures + Puts)",
        "group": "defensive",
        "description": "Short futures against beta exposure and add puts for convexity.",
        "legs": [
            {"action": "sell", "type": "futures", "strike_offset_pct": 0.0, "expiry_preference": "near_month", "quantity_ratio": "beta_weighted"},
            {"action": "buy", "type": "put", "strike_offset_pct": -3.0, "expiry_preference": "near_month", "quantity_ratio": 0.25},
        ],
        "when_to_use": [
            "shock_severity == EXTREME",
            "equity book cannot be reduced fast enough",
            "portfolio gross delta is strongly positive during a crash",
        ],
        "when_not_to_use": [
            "low volatility sideways regime",
            "sufficient put hedges are already in place",
        ],
        "sizing": {"method": "portfolio_beta_calculation", "target_net_delta": 0.0},
        "shock_triggers": ["oil_supply_disruption", "unknown_high_magnitude", "global_recession"],
        "notes": "Emergency neutralization tool.",
    },
    "long_call": {
        "name": "Long Call (Directional Bullish)",
        "group": "aggressive",
        "description": "Buy OTM call on a shock beneficiary.",
        "legs": [
            {"action": "buy", "type": "call", "strike_offset_pct": +3.0, "expiry_preference": "next_monthly", "quantity_ratio": 1.0}
        ],
        "when_to_use": [
            "sector_impact_score > +0.60",
            "INR depreciation shock on IT",
            "oil_price_spike on ONGC or OIL",
            "geopolitical conflict on BEL or BDL",
            "rate_cut_rbi on finance or real estate beneficiaries",
            "IV rank < 40",
        ],
        "when_not_to_use": [
            "IV rank > 70",
            "stock already moved 5%+ before entry",
            "no clear catalyst",
        ],
        "entry_conditions": {"min_beneficiary_sector_score": 0.50, "max_iv_rank": 65, "min_shock_severity": "MODERATE", "entry_timing": "within first 30 minutes of market open after shock"},
        "exit_conditions": {"stop_loss_pct": 50, "target_pct": 200, "max_holding_days": 10},
        "sizing": {"method": "fixed_premium", "max_premium_pct_of_portfolio": 0.5},
        "shock_triggers": ["inr_depreciation", "oil_price_spike", "oil_supply_disruption", "geopolitical_conflict", "rate_cut_rbi", "capex_cycle_acceleration"],
        "preferred_underlyings": ["INFY", "TCS", "HCLTECH", "ONGC", "BEL", "BAJFINANCE"],
        "notes": "Small-sized alpha expression.",
    },
    "bull_call_spread": {
        "name": "Bull Call Spread",
        "group": "aggressive",
        "description": "Buy lower strike call and sell higher strike call for a defined-risk bullish view.",
        "legs": [
            {"action": "buy", "type": "call", "strike_offset_pct": +1.0, "expiry_preference": "next_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "call", "strike_offset_pct": +6.0, "expiry_preference": "next_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "expecting moderate rally (3-7%)",
            "IV rank is elevated (>50)",
            "recovery trade after shock pricing stabilizes",
            "post-budget positive regime",
            "RBI rate cut confirmed",
        ],
        "when_not_to_use": [
            "expecting >10% move",
            "IV rank < 20",
        ],
        "entry_conditions": {"min_beneficiary_score": 0.40, "max_iv_rank": 85, "shock_direction": "BULLISH"},
        "exit_conditions": {"stop_loss_pct": 70, "target_pct": 80, "max_holding_days": 15},
        "sizing": {"method": "notional_pct", "max_pct": 1.0},
        "shock_triggers": ["rate_cut_rbi", "capex_cycle_acceleration", "budget_positive", "fii_inflow", "monsoon_normal"],
        "preferred_underlyings": ["NIFTY", "BANKNIFTY", "NIFTY IT", "sector beneficiaries"],
        "notes": "Preferred defined-risk bullish spread.",
    },
    "call_backspread": {
        "name": "Call Ratio Backspread (1x2)",
        "group": "aggressive",
        "description": "Sell one lower strike call and buy two higher strike calls for breakout convexity.",
        "legs": [
            {"action": "sell", "type": "call", "strike_offset_pct": +2.0, "expiry_preference": "next_monthly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "call", "strike_offset_pct": +5.0, "expiry_preference": "next_monthly", "quantity_ratio": 2.0},
        ],
        "when_to_use": [
            "expecting a big breakout at low net cost",
            "FII massive inflow shock",
            "capex supercycle rerating",
            "IV rank is low",
        ],
        "when_not_to_use": [
            "high IV",
            "range-bound or bearish market",
        ],
        "sizing": {"method": "notional_pct", "max_pct": 1.0},
        "shock_triggers": ["fii_inflow", "capex_cycle_acceleration", "budget_positive", "rate_cut_rbi"],
        "preferred_underlyings": ["NIFTY", "Capital Goods stocks", "BANKNIFTY"],
        "notes": "Asymmetric upside breakout trade.",
    },
    "naked_put_aggressive": {
        "name": "Cash-Secured Put (Aggressive Entry on Dip)",
        "group": "aggressive",
        "description": "Sell an OTM put at a level where the stock would be an acceptable buy.",
        "legs": [
            {"action": "sell", "type": "put", "strike_offset_pct": -7.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0}
        ],
        "when_to_use": [
            "fundamentally strong stock sold off due to macro shock",
            "you want to buy the stock lower",
            "IV rank > 60",
            "post-shock stabilization phase",
            "bellwether name with only macro-driven weakness",
        ],
        "when_not_to_use": [
            "company-specific fraud or governance issue",
            "low IV",
            "portfolio already fully invested",
        ],
        "sizing": {"method": "cash_reserved", "reserve_full_strike_value": True},
        "shock_triggers": ["fii_outflow", "oil_price_spike", "rate_hike_rbi"],
        "preferred_underlyings": ["INFY", "HDFCBANK", "RELIANCE", "TCS"],
        "notes": "Entry-building tactic disguised as options income.",
    },
    "long_straddle": {
        "name": "Long Straddle",
        "group": "volatility",
        "description": "Buy ATM call plus ATM put for a large move in either direction.",
        "legs": [
            {"action": "buy", "type": "call", "strike_offset_pct": 0.0, "expiry_preference": "nearest_weekly_or_monthly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "put", "strike_offset_pct": 0.0, "expiry_preference": "nearest_weekly_or_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "major event with uncertain direction",
            "geopolitical conflict with unclear market path",
            "IV rank < 25",
            "binary event in next 5 days",
        ],
        "when_not_to_use": [
            "IV rank > 50",
            "earnings already released",
            "slow-moving macro events",
        ],
        "entry_conditions": {"max_iv_rank": 45, "min_days_to_event": 2, "max_days_to_expiry": 7, "min_shock_confidence": 0.70},
        "exit_conditions": {"stop_loss_pct": 30, "target_pct": 100, "time_stop": "exit 1 day before event if no move", "max_holding_days": 5},
        "sizing": {"method": "fixed_premium", "max_premium_pct_of_portfolio": 0.75},
        "shock_triggers": ["geopolitical_conflict", "unknown_high_magnitude", "banking_stress"],
        "preferred_underlyings": ["NIFTY", "BANKNIFTY", "individual_binary_event_stocks"],
        "notes": "Use only when volatility is cheap before a real event.",
    },
    "long_strangle": {
        "name": "Long Strangle",
        "group": "volatility",
        "description": "Buy OTM call plus OTM put for a cheaper two-sided volatility trade.",
        "legs": [
            {"action": "buy", "type": "call", "strike_offset_pct": +3.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "put", "strike_offset_pct": -3.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "expect big move but cannot afford straddle premium",
            "pre-event position where 3%+ move is expected",
            "oil supply disruption or geopolitical escalation",
            "IV rank < 30",
        ],
        "when_not_to_use": [
            "IV rank > 50",
            "low magnitude event",
        ],
        "sizing": {"method": "fixed_premium", "max_premium_pct_of_portfolio": 0.5},
        "shock_triggers": ["geopolitical_conflict", "oil_supply_disruption", "global_recession"],
        "notes": "Lower premium than a straddle, but needs a larger move.",
    },
    "calendar_spread_iv": {
        "name": "Calendar Spread (IV Spike Sell)",
        "group": "volatility",
        "description": "Sell near-term rich IV and buy far-term same-strike optionality.",
        "legs": [
            {"action": "sell", "type": "put", "strike_offset_pct": -2.0, "expiry_preference": "nearest_weekly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "put", "strike_offset_pct": -2.0, "expiry_preference": "next_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "IV spiked dramatically on a short-duration shock",
            "near-term IV is above far-term IV",
            "underlying stabilized after panic",
            "geopolitical panic with unchanged fundamentals",
        ],
        "when_not_to_use": [
            "shock is still ongoing",
            "flat IV term structure",
        ],
        "entry_conditions": {"min_vix_level": 22, "min_iv_rank": 70, "iv_term_structure": "inverted"},
        "exit_conditions": {"target": "near-term IV reverts toward far-term IV", "max_holding_days": 7},
        "shock_triggers": ["geopolitical_conflict", "unknown_high_magnitude", "banking_stress"],
        "notes": "Sell panic premium, own calmer back month vol.",
    },
    "vix_spike_put_spread": {
        "name": "VIX Spike Put Spread (Crisis Alpha)",
        "group": "volatility",
        "description": "Aggressive short-term Nifty put spread opened into a VIX spike.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -1.0, "expiry_preference": "nearest_weekly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "put", "strike_offset_pct": -6.0, "expiry_preference": "nearest_weekly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "India VIX > 25 and rising rapidly",
            "Nifty falling > 2%",
            "shock_severity == SEVERE or EXTREME",
        ],
        "when_not_to_use": [
            "VIX < 18",
            "after the crash has already happened",
        ],
        "entry_conditions": {"min_vix_level": 25, "min_nifty_intraday_fall_pct": 2.0, "timing": "within first 30 minutes of crash detection"},
        "sizing": {"method": "fixed_lots", "base_lots": 5, "scale_with_severity": True},
        "shock_triggers": ["oil_supply_disruption", "geopolitical_conflict", "global_recession", "banking_stress"],
        "notes": "Automated crisis alpha extraction.",
    },
    "iron_butterfly": {
        "name": "Iron Butterfly (Range Bound Post-Shock)",
        "group": "volatility",
        "description": "Sell ATM straddle with wings after the shock is fully priced.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "put", "strike_offset_pct": 0.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "call", "strike_offset_pct": 0.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "call", "strike_offset_pct": +5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "IV rank > 70",
            "market has stabilized after shock and should range",
            "shock resolved or ceased",
        ],
        "when_not_to_use": [
            "shock is still ongoing",
            "IV rank < 40",
        ],
        "sizing": {"method": "notional_pct", "max_pct": 2.0},
        "shock_triggers": ["post_resolution"],
        "notes": "Post-shock normalization play.",
    },
    "covered_call": {
        "name": "Covered Call (Yield Generation)",
        "group": "income",
        "description": "Sell OTM call on owned stock to harvest premium.",
        "legs": [
            {"action": "sell", "type": "call", "strike_offset_pct": +5.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0}
        ],
        "when_to_use": [
            "no major shock detected and market is neutral to mildly bullish",
            "stock expected to trade sideways for 2-4 weeks",
            "IV rank > 40",
            "generate monthly yield",
        ],
        "when_not_to_use": [
            "strong bullish catalyst expected",
            "shock_severity > MODERATE",
        ],
        "sizing": {"method": "match_equity_lots"},
        "target_monthly_yield_pct": 1.5,
        "shock_triggers": [],
        "notes": "Default carry strategy when the tape is calm.",
    },
    "iron_condor": {
        "name": "Iron Condor (Sideways Market)",
        "group": "income",
        "description": "Sell OTM call spread and put spread for range-bound premium capture.",
        "legs": [
            {"action": "buy", "type": "put", "strike_offset_pct": -8.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "put", "strike_offset_pct": -4.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "sell", "type": "call", "strike_offset_pct": +4.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
            {"action": "buy", "type": "call", "strike_offset_pct": +8.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "no shock detected and range expected for 15-30 days",
            "IV rank > 50",
            "post-shock stabilization phase",
            "between major event catalysts",
        ],
        "when_not_to_use": [
            "any shock severity > LOW",
            "IV rank < 30",
            "within 7 days of a major event",
        ],
        "entry_conditions": {"max_shock_severity": "LOW", "min_iv_rank": 40, "days_to_expiry_range": [15, 30]},
        "exit_conditions": {"stop_loss": "exit if either short strike is breached", "target_pct": 50, "max_holding_days": 21},
        "sizing": {"method": "notional_pct", "max_pct": 3.0},
        "shock_triggers": [],
        "notes": "Bread-and-butter neutral income strategy.",
    },
    "diagonal_spread": {
        "name": "Diagonal Spread (LEAPS + Short Near-Term)",
        "group": "income",
        "description": "Buy longer-dated ITM call and sell shorter-dated OTM call against it.",
        "legs": [
            {"action": "buy", "type": "call", "strike_offset_pct": -5.0, "expiry_preference": "three_month", "quantity_ratio": 1.0},
            {"action": "sell", "type": "call", "strike_offset_pct": +3.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0},
        ],
        "when_to_use": [
            "bullish long term but want lower cost through call sale",
            "IT during INR depreciation",
            "Capital Goods during capex cycle",
        ],
        "when_not_to_use": [
            "expecting very sharp short-term move",
            "illiquid far-month options",
        ],
        "sizing": {"method": "fixed_premium", "max_premium_pct_of_portfolio": 1.0},
        "shock_triggers": ["inr_depreciation", "capex_cycle_acceleration"],
        "notes": "Capital-efficient long replacement structure.",
    },
    "put_write_cash_secured": {
        "name": "Put Write Program (Systematic Entry Builder)",
        "group": "income",
        "description": "Systematic OTM put sale on high-quality names for discounted entry and carry.",
        "legs": [
            {"action": "sell", "type": "put", "strike_offset_pct": -8.0, "expiry_preference": "nearest_monthly", "quantity_ratio": 1.0}
        ],
        "when_to_use": [
            "no active shock detected",
            "IV rank > 45",
            "on names you want to own for the long term",
            "run systematically as a program",
        ],
        "when_not_to_use": [
            "during active shock with sector score < -0.50",
            "stock has negative company signal",
        ],
        "sizing": {"method": "cash_reserved", "max_total_obligation_pct_of_portfolio": 30.0},
        "shock_triggers": [],
        "notes": "Background premium harvesting on quality names.",
    },
}
