#!/usr/bin/env python3
"""
Dynamic liquidity monitoring for capacity-aware execution.

Tracks rolling ADV, classifies liquidity tiers, detects large ADV drops,
and emits actionable alerts for portfolio risk controls.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Dict, Iterable, List, Optional, Tuple

from src.intelligence.adv_database import ADVData, ADVDatabase, LiquidityTier
from src.intelligence.position_governor import PositionGovernor


@dataclass(frozen=True)
class LiquidityAlert:
    """Structured liquidity alert generated by the monitor."""

    symbol: str
    timestamp: datetime
    severity: str
    alert_type: str
    message: str
    previous_adv: float
    current_adv: float
    drop_pct: float
    previous_tier: Optional[str] = None
    current_tier: Optional[str] = None


class LiquidityMonitor:
    """
    Dynamic ADV monitor with automatic alerts and limit adjustment hooks.

    Acceptance coverage:
    - Daily ADV updates via rolling windows (delegated to ADVDatabase).
    - ADV drops >30% trigger position reduction alerts.
    - Tier changes are detected and surfaced.
    - Position limit checks can be re-evaluated with new tiers.
    """

    def __init__(
        self,
        adv_database: ADVDatabase,
        drop_threshold: float = 0.30,
        near_limit_threshold: float = 0.85,
    ) -> None:
        self.adv_database = adv_database
        self.drop_threshold = float(drop_threshold)
        self.near_limit_threshold = float(near_limit_threshold)
        self.latest_adv: Dict[str, ADVData] = {}
        self.previous_adv: Dict[str, ADVData] = {}

    def update_daily_adv(
        self,
        symbols: Iterable[str],
        as_of_date: Optional[datetime] = None,
    ) -> Dict[str, ADVData]:
        """Refresh ADV snapshots for symbols and retain prior state for delta checks."""

        requested = list(dict.fromkeys(str(s) for s in symbols))
        old = self.latest_adv.copy()
        fetched = self.adv_database.get_adv_for_symbols(requested, as_of_date=as_of_date)
        new: Dict[str, ADVData] = {}
        for symbol, data in fetched.items():
            if data is not None:
                new[symbol] = data

        self.previous_adv = {s: old[s] for s in requested if s in old}
        self.latest_adv.update(new)
        return {s: self.latest_adv[s] for s in requested if s in self.latest_adv}

    def classify_liquidity_tiers(self, symbols: Iterable[str]) -> Dict[str, str]:
        """Return current liquidity tier labels for symbols."""

        tiers: Dict[str, str] = {}
        for symbol in symbols:
            data = self.latest_adv.get(symbol)
            if data is None:
                data = self.adv_database.calculate_rolling_adv(symbol)
            if data is None:
                tiers[str(symbol)] = "unknown"
            else:
                tiers[str(symbol)] = data.liquidity_tier.value
        return tiers

    def detect_liquidity_alerts(
        self,
        symbols: Iterable[str],
        timestamp: Optional[datetime] = None,
    ) -> List[LiquidityAlert]:
        """
        Detect ADV-drop and tier-transition alerts.

        - ADV drop > drop_threshold -> HIGH alert with reduction recommendation.
        - Tier downgrade -> MEDIUM alert.
        """

        now = timestamp or datetime.now()
        alerts: List[LiquidityAlert] = []

        for symbol in symbols:
            key = str(symbol)
            cur = self.latest_adv.get(key)
            prev = self.previous_adv.get(key)
            if cur is None or prev is None:
                continue

            prev_adv = float(prev.adv_21d)
            cur_adv = float(cur.adv_21d)
            if prev_adv <= 0:
                continue

            drop_pct = max(0.0, (prev_adv - cur_adv) / prev_adv)
            if drop_pct > self.drop_threshold:
                alerts.append(
                    LiquidityAlert(
                        symbol=key,
                        timestamp=now,
                        severity="high",
                        alert_type="adv_drop",
                        message=(
                            f"ADV fell by {drop_pct:.1%}; reduce position sizing until liquidity normalizes."
                        ),
                        previous_adv=prev_adv,
                        current_adv=cur_adv,
                        drop_pct=drop_pct,
                        previous_tier=prev.liquidity_tier.value,
                        current_tier=cur.liquidity_tier.value,
                    )
                )

            if cur.liquidity_tier != prev.liquidity_tier:
                alerts.append(
                    LiquidityAlert(
                        symbol=key,
                        timestamp=now,
                        severity="medium",
                        alert_type="tier_change",
                        message=(
                            f"Liquidity tier changed {prev.liquidity_tier.value} -> {cur.liquidity_tier.value};"
                            " recompute position limits."
                        ),
                        previous_adv=prev_adv,
                        current_adv=cur_adv,
                        drop_pct=drop_pct,
                        previous_tier=prev.liquidity_tier.value,
                        current_tier=cur.liquidity_tier.value,
                    )
                )

        return alerts

    def evaluate_portfolio_limit_utilization(
        self,
        weights: Dict[str, float],
        portfolio_value: float,
        governor: PositionGovernor,
        as_of_date: Optional[datetime] = None,
    ) -> Tuple[Dict[str, float], List[LiquidityAlert]]:
        """
        Evaluate position-limit utilization and generate near-limit alerts.

        Returns:
        - utilization: symbol -> used_limit_fraction (0..+inf)
        - alerts: warning/high alerts for nearing or breaching limits
        """

        utilization: Dict[str, float] = {}
        alerts: List[LiquidityAlert] = []
        now = datetime.now()

        for symbol, weight in weights.items():
            lim = governor.calculate_max_position(symbol, as_of_date=as_of_date)
            if lim.max_position_value <= 0:
                utilization[symbol] = 0.0
                continue

            pos_value = abs(float(weight)) * float(portfolio_value)
            used = pos_value / lim.max_position_value
            utilization[symbol] = float(used)

            if used >= 1.0:
                alerts.append(
                    LiquidityAlert(
                        symbol=symbol,
                        timestamp=now,
                        severity="high",
                        alert_type="limit_breach",
                        message=f"Position uses {used:.1%} of liquidity limit; reduce exposure.",
                        previous_adv=float(lim.adv_used),
                        current_adv=float(lim.adv_used),
                        drop_pct=0.0,
                        current_tier=lim.liquidity_tier.value,
                    )
                )
            elif used >= self.near_limit_threshold:
                alerts.append(
                    LiquidityAlert(
                        symbol=symbol,
                        timestamp=now,
                        severity="warning",
                        alert_type="near_limit",
                        message=f"Position uses {used:.1%} of liquidity limit; monitor closely.",
                        previous_adv=float(lim.adv_used),
                        current_adv=float(lim.adv_used),
                        drop_pct=0.0,
                        current_tier=lim.liquidity_tier.value,
                    )
                )

        return utilization, alerts

    def recommend_reduction_factor(self, symbol: str) -> float:
        """
        Return position reduction multiplier for a symbol based on latest alerts.

        Rule: if ADV drop exceeds threshold, recommend 50% position reduction.
        """

        cur = self.latest_adv.get(symbol)
        prev = self.previous_adv.get(symbol)
        if cur is None or prev is None or prev.adv_21d <= 0:
            return 1.0

        drop_pct = max(0.0, (prev.adv_21d - cur.adv_21d) / prev.adv_21d)
        if drop_pct > self.drop_threshold:
            return 0.5
        return 1.0

