#!/usr/bin/env python3
"""
AUTOMATED MIGRATION SCRIPT
Generated by MigrationHelper to fix hardcoded references
"""

import os
import re
import shutil

def backup_file(file_path):
    backup_path = file_path + '.backup'
    shutil.copy2(file_path, backup_path)
    print(f'Backed up {file_path} to {backup_path}')

def migrate_file(file_path, replacements):
    backup_file(file_path)
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    for old_pattern, new_replacement in replacements:
        content = re.sub(old_pattern, new_replacement, content)
    
    with open(file_path, 'w') as f:
        f.write(content)
    
    print(f'Migrated {file_path}')

# Migration mappings
migrations = {
    'src/validation/universe_manager.py': [
        (r'data/raw/', '# TODO: Replace data/raw/'),
        (r'data/raw/', '# TODO: Replace data/raw/'),
    ],
    'src/validation/final_checkpoint_validation.py': [
        (r'reports/', 'get_report_path('system', filename)'),
    ],
    'src/validation/production_hardening.py': [
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
    ],
    'src/validation/enhanced_portfolio_simulator.py': [
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
        (r'data/simulation/', '# TODO: Replace data/simulation/'),
    ],
    'src/validation/reality_check_engine_backup.py': [
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
    ],
    'src/validation/reality_check_engine.py': [
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
    ],
    'src/validation/performance_benchmarking_system.py': [
    ],
    'src/validation/final_system_validation_certification.py': [
        (r'reports/', 'get_report_path('system', filename)'),
    ],
    'src/validation/data_integrity.py': [
        (r'data/integrity/', '# TODO: Replace data/integrity/'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/integrity/', '# TODO: Replace data/integrity/'),
    ],
    'src/validation/enhanced_walk_forward_engine.py': [
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
    ],
    'src/validation/walk_forward_engine.py': [
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
    ],
    'src/validation/production_readiness_certificate.py': [
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/execution/', '# TODO: Replace data/execution/'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
    ],
    'src/validation/strategy_deduplication.py': [
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/validation/', 'get_data_path('validation', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
    ],
    'src/automation/snapshot_scheduler.py': [
        (r'logs/', '# TODO: Replace logs/'),
        (r'data/processed/', 'get_data_path('processed', filename)'),
    ],
    'src/automation/northstar_scheduler.py': [
    ],
    'src/preprocessing/macro_cleaner.py': [
    ],
    'src/preprocessing/market_internals.py': [
    ],
}

def main():
    print('Starting migration...')
    
    for file_path, replacements in migrations.items():
        if os.path.exists(file_path):
            migrate_file(file_path, replacements)
        else:
            print(f'File not found: {file_path}')
    
    print('Migration complete!')

if __name__ == '__main__':
    main()